version: "3.7"
services:
  database:
    image: postgres
    networks:
      - fullstack
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telegrambot
    ports:
      - "54320:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://root:root@database:5432/telegrambot?sslmode=disable",
        "up",
        "3",
      ]
    links:
      - database
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - fullstack
    ports:
      - "80:80"
volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
